### find alle opskrifter
GET {{url}}/recipes
### Find opskrifter med id som er 1
GET {{url}}/recipes/1
### Find opskrifter med rice
GET {{url}}/recipes/name/rice
### Find opskrifter med 4 portioner
GET {{url}}/recipes/servings/4 servings

### Lav en ny opskrift med pasta
POST {{url}}/recipes
Content-Type: application/json

{
  "recipeName": "Pasta",
  "servings": "3 servings",
  "instructions": "Boil Pasta, Add Tomato Sauce, Add Cheese",
  "recipeIngredients": [
    {
      "ingredient": {
        "ingredientName": "Pasta"
      },
      "amount": "200g"
    },
    {
      "ingredient": {
        "ingredientName": "Tomato Sauce"
      },
      "amount": "100ml"
    },
    {
      "ingredient": {
        "ingredientName": "Cheese"
      },
      "amount": "50g"
    }
  ]
}

### Ændr chicken and rice til noodles
PUT {{url}}/recipes/1
Content-Type: application/json

{
  "recipeName": "Noodles",
  "servings": "2 servings",
  "instructions": "Boil Noodles, Add Soy Sauce, Add Vegetables",
  "recipeIngredients": [
    {
      "ingredient": {
        "ingredientName": "Noodles"
      },
      "amount": "150g"
    },
    {
      "ingredient": {
        "ingredientName": "Soy Sauce"
      },
      "amount": "50ml"
    },
    {
      "ingredient": {
        "ingredientName": "Vegetables"
      },
      "amount": "100g"
    }
  ]
}

###
DELETE {{url}}/recipes/1

### Lav en ny ingrediens
POST {{url}}/ingredients
Content-Type: application/json

{
  "ingredientName": "Tahini"
}

### Ændr garlic til noget andet
PUT {{url}}/ingredients/4
Content-Type: application/json

{
  "ingredientName": "Ginger"
}
### Slet chicken
DELETE {{url}}/ingredients/1

### mangler to delete nederst, put på linje linje 41 og get på linje 6