### find alle opskrifter
GET {{url}}/recipes
### Find opskrifter med id som er 1
GET {{url}}/recipes/1
### Find opskrifter med rice
GET {{url}}/recipes/name/rice
### Find opskrifter med 4 portioner
GET {{url}}/recipes/servings/4 servings

### Lav en ny opskrift med pasta
POST {{url}}/recipes
Content-Type: application/json

{
  "recipeName": "Garlic Super Chicken",
  "servings": "4 servings",
  "instructions": "Cook chicken with garlic.",
  "recipeIngredients": [
    {
      "ingredient": {
        "ingredientName": "Chicken"
      },
      "amount": "250g"
    },
    {
      "ingredient": {
        "ingredientName": "Garlic"
      },
      "amount": "2 cloves"
    }
  ]
}


### Ændr chicken and rice til Chicken and Onion Stir-Fry
PUT {{url}}/recipes/1
Content-Type: application/json

{
  "recipeName": "Chicken and Onion Stir-Fry",
  "servings": "2 servings",
  "instructions": "Heat oil in a pan, sauté onions until translucent, add chicken and cook until golden brown, season to taste.",
  "recipeIngredients": [
    {
      "ingredient": {
        "ingredientName": "Chicken"
      },
      "amount": "200g"
    },
    {
      "ingredient": {
        "ingredientName": "Onion"
      },
      "amount": "1 large"
    }
  ]
}

###
DELETE {{url}}/recipes/1

### Lav en ny ingrediens
POST {{url}}/ingredients
Content-Type: application/json

{
  "ingredientName": "Tahini"
}

### Ændr garlic til noget andet
PUT {{url}}/ingredients/4
Content-Type: application/json

{
  "ingredientName": "Ginger"
}
### Slet chicken
DELETE {{url}}/ingredients/1

### mangler recipe delete, og post recipe