GET {{url}}/recipes

###

GET {{url}}/recipes/1

###

GET {{url}}/recipes/name/Rice

###

GET {{url}}/recipes/servings/4 servings

###

POST {{url}}/recipes
Content-Type: application/json

{
  "recipeName": "Pasta",
  "servings": "3 servings",
  "instructions": "Boil Pasta, Add Tomato Sauce, Add Cheese",
  "recipeIngredients": [
    {
      "ingredient": {
        "ingredientName": "Pasta"
      },
      "amount": "200g"
    },
    {
      "ingredient": {
        "ingredientName": "Tomato Sauce"
      },
      "amount": "100ml"
    },
    {
      "ingredient": {
        "ingredientName": "Cheese"
      },
      "amount": "50g"
    }
  ]
}

###

PUT {{url}}/recipes/1
Content-Type: application/json

{
  "recipeName": "Noodles",
  "servings": "2 servings",
  "instructions": "Boil Noodles, Add Soy Sauce, Add Vegetables",
  "recipeIngredients": [
    {
      "ingredient": {
        "id": 1,
        "ingredientName": "Noodles"
      },
      "amount": "150g"
    },
    {
      "ingredient": {
        "id": 2,
        "ingredientName": "Soy Sauce"
      },
      "amount": "50ml"
    },
    {
      "ingredient": {
        "id": 3,
        "ingredientName": "Vegetables"
      },
      "amount": "100g"
    }
  ]
}

###

DELETE {{url}}/recipes/1


